# Generated by Django 4.0.1 on 2022-04-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
