# Generated by Django 4.0.1 on 2022-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=512)),
                ('starting_bid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('img_url', models.URLField()),
            ],
        ),
    ]
