# Generated by Django 4.0.3 on 2022-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
