# Generated by Django 4.0.1 on 2022-04-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='start_bid',
        ),
    ]
